### ISSUE TITLE
Is there any way to "Add" views, etc?

### ISSUE THREAD

**Issue by mralexgray** [JustSid/JUCollectionView#2]
I have tried changing the response of the delegate's `numberOfCellsInCollectionView` and sending the instance `reload`… but that doesn't seem to accomplish much.. even if I provide valid views, or trick the index into dequeing an existing view for that new, higher index..

i also tried upping, for intsance, the `desiredNumberOfRows`, etc. with no success?

does this hinge on the `begin` and `commit` methods, by chance?  or is the collection view just not designed to be mutable, etc?

**Comment by JustSid** [comment]
It works for me and the view should definitely be mutable! I just tested it with the demo app by adding more objects to the `content` array and then calling `reloadData` every few seconds, the new cells get displayed perfectly! Also works the other way around when removing objects.

Can you post a small example to reproduce the problem?

Btw, the `beginChanges` and `commitChanges` methods are there in case you need to make a larger amount of changes and force the collection view to not reload its data every time but only add the end when you send it `commitChanges`, so you don't need to call it if just want it to display your new cells!
